# Generated by Django 4.1.6 on 2023-02-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.user', verbose_name='автор')),
                ('category_id', models.ManyToManyField(related_name='category', to='category.category', verbose_name='категории')),
                ('tags', models.ManyToManyField(related_name='tags', to='category.tag', verbose_name='тэг')),
            ],
        ),
    ]
